import React from "react"
import "./index.css"

function Policy() {
    return (
        <main class="teeapp-main row">
            <div class="post-body docs-content">
                <h1 class="page-header text-uppercase text-center"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>AGREEMENT TO PROVIDE AND USE THE SOCIAL NETWORK SERVICE TEEAPP</font></font></h1>
                <br />
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 1. GENERAL PRINCIPLES</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Before registering an account to use the service on the TeeApp Social Network (“</font></font><strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Service</font></font></strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>), you acknowledge that you have read, understood and agreed to all provisions of this Agreement for the Provision and Use of Social Networking Services TeeApp (hereinafter referred to as ““</font></font><strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Agree</font></font></strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>”) through completing the TeeApp Social Network account registration. </font><font style={{ verticalAlign: "inherit" }}>You accept without limitation and/or in relation to all terms and conditions below, from the time you first use the Service.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>When considering the use of Services provided by TeeApp Technology Joint Stock Company (hereinafter referred to as "</font></font><strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>we</font></font></strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>" or "</font></font><strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>TeeApp</font></font></strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>"), you represent that you are of legal age to enter into a binding agreement, and are not a person prohibited from receiving the Service under Vietnamese law, or that you have obtained prior consent of your parent or legal guardian to use the Service in accordance with and in accordance with this Agreement.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>At the same time, when registering for an account and using the Service, you also represent and accept that:
                    </font></font><ul>
                            <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>If you want to identify your account, you will provide complete and accurate information about your full name; </font><font style={{ verticalAlign: "inherit" }}>date of birth; </font><font style={{ verticalAlign: "inherit" }}>identity card/passport/citizen identification number (“ID”), date of issue, place of issue</font></font><strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Identification</font></font></strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>, and be responsible for the information you provide when making the registration as well as amending and supplementing this information;</font></font></li>
                            <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>All communications, data, text, software, music, sound, photographs, graphics, video, mail or other materials (collectively, ""</font></font><strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Information</font></font></strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>"), whether publicly posted or privately transmitted, is primarily the responsibility of the person creating such Information. We have a system in place to moderate the content of the Shared Information as well as a detection mechanism. and handle violations of the Information provided by different users on the TeeApp Social Network in accordance with the laws of Vietnam;</font></font></li>
                            <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>You may legally and legally share Information in the formats we default to in areas where permitted. </font><font style={{ verticalAlign: "inherit" }}>As a user, you are responsible for your own communications and are solely responsible for the results of sharing. </font><font style={{ verticalAlign: "inherit" }}>We do not represent, endorse or warrant the truthfulness or accuracy of the Information shared.</font></font></li>
                        </ul>
                    </li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>For Information protected by intellectual property rights such as photos and videos (“</font></font><strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>IP Information</font></font></strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>"), you separately grant us the following right: you grant us a worldwide, non-exclusive, transferable, sub-licensable and free license to use any IP Information you post up ("</font></font><strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>IP License</font></font></strong><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>"). </font><font style={{ verticalAlign: "inherit" }}>This IP License expires when you delete IP Information or an account, unless Your Information has been shared by you yourself with others who have not deleted such Information on the TeeApp Social Network.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>By sharing Information on TeeApp Social Networks, you agree to grant us the right to use and share such Information on other platforms of the TeeApp ecosystem under our control or other media. mass.
                    </font></font></li>

                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 2. REGULATIONS ON NAME OF DELIVERY ACCOUNTS</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Accounts and characters are not allowed to be named after celebrities, leaders, terrorists, fascists, criminals, and the names of individuals and organizations that oppose the State of the Socialist Republic of Vietnam. Socialist Republic of Vietnam, which is detrimental to national security and social order and safety.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Account names or characters must not be identical or confusingly similar to the initials and full names of state agencies, political organizations, socio-political organizations, socio-political organizations - Vietnamese professions, social organizations, socio-professional organizations and international organizations, without the permission of such agencies or organizations.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Do not use the same or confusing account names or characters to impersonate other individuals or organizations for the purpose of giving false information, distorting, slandering, or insulting the organization's reputation and honor. and the dignity of other individuals.
                    </font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Do not name the account, the character infringes the intellectual property rights.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>No names containing words/phrases that may cause confusion with TeeApp ecosystem platforms under TeeApp's control shall not be permitted without TeeApp's written consent.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Accounts that violate naming rules will be permanently locked and/or deleted without notice.</font></font></li>
                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 3. REGULATIONS ON AGENTS</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Do not use images that imply incitement to violence, lewdness, debauchery, crimes, social evils, superstition, destruction of the nation's fine customs and traditions.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Do not use images or images that are offensive to celebrities, national heroes, leaders of the Party and State of Vietnam and leaders of international organizations.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Do not use images containing signs that are identical or confusingly similar to symbols, flags, badges, abbreviations, full names of state agencies, political organizations, political organizations - social organizations, socio-political-professional organizations, social organizations, socio-professional organizations of Vietnam and international organizations that offend the reputation of these organizations.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Do not use images related to religion that provoke and divide the great national unity bloc, going against Vietnam's religious policy.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Do not use pictures of criminals, terrorists, fascism, and photos or images depicting individuals and organizations opposing the State of the Socialist Republic of Vietnam, causing harm to national security and order. social self-security.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Do not use photos that offend the reputation of the organization, the honor and dignity of other individuals.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Do not use images containing words/phrases, logos, signs that are identical or confusingly similar to platforms in the TeeApp ecosystem under TeeApp's management without TeeApp's written consent. .</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Do not use images that infringe intellectual property rights.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Accounts that violate the avatar policy will be permanently locked and/or deleted without notice.</font></font></li>
                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 4. INFORMATION PROHIBITED TO SHARE, EXCHANGE, SHARE ON TEEAPP SOCIAL NETWORKS</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Information against the State of the Socialist Republic of Vietnam; </font><font style={{ verticalAlign: "inherit" }}>causing harm to national security, social order and safety; </font><font style={{ verticalAlign: "inherit" }}>organizing, operating, colluding, instigating, bribing, deceiving, enticing, training and training people against the State of the Socialist Republic of Vietnam.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Propaganda of war and terrorism.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Instigating, enticing or inciting others to commit crimes.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Distorting history, denying revolutionary achievements, undermining the great unity bloc of the whole nation, insulting religion, discriminating against gender, race, religion; </font><font style={{ verticalAlign: "inherit" }}>causing hatred and conflict among ethnic groups, ethnic groups and religions.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Information inciting violence, lewdness, debauchery, crimes, social evils, superstition, destruction of the nation's fine customs and traditions.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Disclosure of state secrets, military secrets, security, economic, foreign affairs and other secrets prescribed by Vietnamese law.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Information that distorts, slanders, insults the reputation of the organization, honor and dignity of the individual.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Advertising, propagating, trading in prohibited goods and services; </font><font style={{ verticalAlign: "inherit" }}>Dissemination of journalistic, literary, artistic and publication works is prohibited.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Forging organizations and individuals and spreading fake and untrue information infringing upon the legitimate rights and interests of organizations and individuals.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Information that violates intellectual property rights.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Other Information that violates the legitimate rights and interests of individuals and organizations.</font></font></li>
                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 5. OTHER PROHIBITED ACTS</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Illegally obstructing the operation of the Vietnamese national domain name server system ".vn", the lawful operation of the equipment system providing Internet services and information on the network.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Illegally obstructing the provision and access of lawful information, the provision and use of lawful services on the Internet by organizations and individuals.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Illegally using passwords and cryptographic keys of organizations and individuals; </font><font style={{ verticalAlign: "inherit" }}>private information, personal information and Internet resources.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Creating unauthorized links to legitimate domain names of organizations and individuals. </font><font style={{ verticalAlign: "inherit" }}>Create, install and distribute malware and computer viruses; </font><font style={{ verticalAlign: "inherit" }}>illegally infiltrate, gain control of information systems, create attack tools on the Internet.
                    </font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Use any program, tool or other means to interfere with TeeApp's services.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Distributing, spreading or promoting any activity to interfere, destroy or infiltrate the data of the provided service or the server system.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Unauthorized login or attempt to log in illegally or cause damage to the server system.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Harass, curse, annoy or engage in any unethical behavior towards other users.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Acts and attitudes that damage the reputation of TeeApp and/or TeeApp's services in any way or manner.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Promote any product/service in any way without complying with TeeApp's service provision and use agreement and advertising policy.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Gambling and gambling organization on the TeeApp Social Network.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Other prohibited acts as prescribed by Vietnamese law in each field.</font></font></li>

                </ol>

                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 6. RIGHTS OF TEEAPP SOCIAL NETWORK USERS</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>You have the right to change and supplement your registered personal information and password.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>You are shown how to set a secure password; </font><font style={{ verticalAlign: "inherit" }}>enter important information to protect the account; </font><font style={{ verticalAlign: "inherit" }}>Use a linked account to log into your account.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>You are entitled to donate your TeeApp Social Network account to others. </font><font style={{ verticalAlign: "inherit" }}>The right to be given to an account is only applied to an account that has fully and accurately registered with account information in accordance with this Agreement.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Confidentiality of personal information is guaranteed according to the provisions of this Agreement and the Privacy Policy of Personal Information on Social Networks TeeApp. </font><font style={{ verticalAlign: "inherit" }}>Accordingly, the personal information you provide will only be used by TeeApp to control activities on the TeeApp Social Network and will not be provided to any other third party without the consent of TeeApp. you, unless there is a request from a competent State agency in accordance with the provisions of Vietnamese law.
                    </font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>To be entitled to request TeeApp to provide necessary information in connection with the use of the Service.</font></font></li>
                </ol>

                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 7. OBLIGATIONS OF TEEAPP SOCIAL NETWORK USERS</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>To receive support from TeeApp, your account must be fully registered with truthful and accurate information.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>You are responsible for the security of your account information on the TeeApp Social Network, including: Password, account protection phone number, ID information, account protection email. </font><font style={{ verticalAlign: "inherit" }}>If the above information is disclosed due to your own carelessness or any other personal security error, you must accept the arising risks. </font><font style={{ verticalAlign: "inherit" }}>We will base on the information available in the account to determine the account owner if there is a dispute and we will not be responsible for any losses incurred. </font><font style={{ verticalAlign: "inherit" }}>Information The ID registered in the account is the most important information to prove the owner of the account.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>You agree to immediately notify TeeApp of any unauthorized use of your account and password or any other breach of security by submitting a support request at </font></font><a href="https://hotro.teeapp.vn/" class="text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>https http://hotro.teeapp.vn/</font></font></a><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}> .</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>We care about the safety and privacy of all members who register for an account and use the Service on the TeeApp Social Network, especially minors and wards. </font><font style={{ verticalAlign: "inherit" }}>Therefore, if you are a parent or legal guardian, it is your responsibility to determine which Information on the TeeApp Social Network is appropriate for your child or your ward. </font><font style={{ verticalAlign: "inherit" }}>Similarly, if you are a minor or ward, you must consult your parent or legal guardian to determine whether the Information you use/access on the TeeApp Social Network suitable for you or not.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>You must be fully responsible before Vietnamese law for the Information you share, transmit, send, store on the TeeApp Social Network, the Internet, or the telecommunications network. </font><font style={{ verticalAlign: "inherit" }}>If you violate intellectual property rights, you may be liable for civil damages, administrative fines, criminal prosecution in accordance with the law.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>You must indemnify TeeApp in its entirety in the event of your breach of any provision of this Agreement and/or a breach of law resulting in loss, damage to property and reputation. of TeeApp.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Comply with regulations on information safety, information security and other relevant regulations in accordance with the laws of Vietnam and this Agreement.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Comply with other responsibilities and obligations of users of social networks, Internet and telecommunications networks in accordance with Vietnamese law.</font></font></li>
                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 8. TEEAPP RIGHTS</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>If you provide any information that is not truthful, inaccurate, or if TeeApp has grounds to suspect that the information is inaccurate, or if you violate any provision of this Agreement, TeeApp may reserves the right to terminate or delete your account without your consent and without any liability to you. </font><font style={{ verticalAlign: "inherit" }}>At the same time, TeeApp reserves the right to refuse to support and process requests for your account.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>If you have comments, posts that are meaningless and/or comments, posts that continuously annoy other users, TeeApp reserves the right to disable your comments and/or postings in 01(one) days, 03(three) days, or longer, depending on the severity of the violation. </font><font style={{ verticalAlign: "inherit" }}>In case you violate multiple times, TeeApp will lock your account for at least 30 (thirty) days, or more depending on the nature and severity of the violation.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>When TeeApp discovers your violations in the process of using the Service such as unauthorized access, sharing, transmission of Information prohibited under this Agreement and/or the provisions of Vietnamese law, or other errors affect the legitimate rights and interests of TeeApp and/or the relevant individual or organization, TeeApp has the right to: (i) deprive you of all rights in this Agreement, including termination, delete your account without your consent and without incurring any liability to you; </font><font style={{ verticalAlign: "inherit" }}>and/or (ii) use the information you provide when registering for an account to transfer to the authorities to handle these violations in accordance with the laws of Vietnam.</font></font></li>
                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 9. TEEAPP RESPONSIBILITIES</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Responsible for supporting you in the process of using the Service.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Receive and resolve your complaints and disputes arising in the process of using the Service within the jurisdiction of TeeApp in accordance with the laws of Vietnam. </font><font style={{ verticalAlign: "inherit" }}>However, we only support, receive and resolve complaints and disputes for registered accounts with complete, honest and accurate information.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Be responsible for keeping your personal information confidential in accordance with the provisions of this Agreement, the Privacy Policy of Personal Information on Social Networks TeeApp and the provisions of Vietnamese law. </font><font style={{ verticalAlign: "inherit" }}>We do not sell or exchange your personal information with third parties, except at the request of a competent State agency in accordance with the laws of Vietnam and/or the cases prescribed by law. in this Agreement.</font></font></li>
                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 10. MECHANISM FOR HANDLING VIOLATIONS</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>If you breach this Agreement, depending on the severity of the breach, we will either temporarily or permanently lock your account or delete it permanently, stripping you of all rights to the Services and will request competent agencies to handle violations in accordance with Vietnamese law.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>In case your violation is not specified in this Agreement, depending on the nature and seriousness of the violation, TeeApp will unilaterally and completely decide on the level of sanction that TeeApp considers reasonable.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>If there is a complaint about Infringing Information and/or any other issue related to the violation handling mechanism set forth in this Agreement, please submit a support request at </font></font><a href="https://hotro.teeapp.vn/" class="text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>https:/ /hotro.teeapp.vn/</font></font></a>                                </li>
                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 11. WARNING ABOUT RISKS WHEN STORE, EXCHANGE AND SHARE INFORMATION ON LINE</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>When you register, use the login feature in connection with third-party platforms and applications, it means that your information will be shared with third parties, based on consent. your. </font><font style={{ verticalAlign: "inherit" }}>By accepting this sharing, you also accept the associated risks. </font><font style={{ verticalAlign: "inherit" }}>In this case, you agree and accept TeeApp's exclusion of liability related to your information and data being shared with third parties.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>If there is a risk, damage in case of force majeure including but not limited to electrical short, damage to hardware, software, problem of Internet transmission or due to natural disaster, fire, strike, change change of law, the user must accept such risks and damages. </font><font style={{ verticalAlign: "inherit" }}>TeeApp commits to make efforts to minimize the risks and damages arising, but we will not bear any responsibility arising in these cases.
                    </font></font></li>
                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 12. APPLICABLE LAW AND DISPUTE SETTLEMENT AGENCIES</font></font></h3>
                <p><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>This Agreement is governed by the laws of Vietnam. </font><font style={{ verticalAlign: "inherit" }}>Any dispute arising during your use of the Service will be resolved in the competent court of Vietnam, in accordance with the applicable laws of Vietnam.</font></font></p>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 13. DURATION FOR SETTLEMENT OF COMPLAINTS AND DISPUTES</font></font></h3>
                <p><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Any claim or dispute arising from this Agreement, within TeeApp's jurisdiction, must be submitted to TeeApp within 01 (one) month from the date of occurrence of the act leading to such complaint or dispute. .</font></font></p>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 14. CONDITIONS AND METHODS OF SETTLEMENT OF COMPLAINTS AND DISPUTES</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>We only support and resolve your complaints and disputes within the jurisdiction of TeeApp in accordance with the laws of Vietnam, provided that you have fully, honestly and accurately recorded information when registering an account. .</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>For disputes between users or between users and TeeApp, we will base on the system's records to resolve. </font><font style={{ verticalAlign: "inherit" }}>Accordingly, we will protect the maximum interests of users who register full information according to regulations.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>When there is a complaint or dispute between you and other users on the TeeApp Social Network or between you and TeeApp, you can send a request to resolve the complaint or dispute to TeeApp at </font></font><a href="https://hotro.teeapp.vn " class="text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>https://hotro.teeapp .VN</font></font></a>                                </li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Unless otherwise provided by Vietnamese law, TeeApp's decision to settle complaints and disputes is final and effective.</font></font></li>
                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 15. EXCLUSION OF OBLIGATIONS AND INSPECTIONS</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>You agree to exclude TeeApp from all liabilities, liabilities, and proceedings arising from your breach in the course of using the Service.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>You must indemnify TeeApp for all damages, in the event you commit a breach of this Agreement and/or a breach of law resulting in loss or damage to TeeApp's property and reputation, including including costs related to the settlement such as court fees, attorneys' fees, consultants' fees and other costs related to the settlement of the case.</font></font></li>
                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 16. COLLECTION, PROCESSING PERSONAL DATA</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>The account registration process using the TeeApp Social Network requires you to provide personal information and a password. </font><font style={{ verticalAlign: "inherit" }}>Whether or not you provide other information to us is up to you.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>We do not use your information for illegal purposes. </font><font style={{ verticalAlign: "inherit" }}>We are entitled to provide your information to third parties in the following cases, including but not limited to:
                    </font></font><ul>
                            <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>We have your consent;</font></font></li>
                            <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>When you register, use the login feature in connection with third-party platforms and applications, and you consent to TeeApp providing your information to such third parties;</font></font></li>
                            <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>At the request of a competent State agency;</font></font></li>
                        </ul>
                    </li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>In the course of using the Service, you agree to receive all notices and advertisements from TeeApp related to the Service via email, postal mail or your phone. </font><font style={{ verticalAlign: "inherit" }}>In the event that you register to use a service provided by a third party, your information will be shared with the third party, based on your consent. </font><font style={{ verticalAlign: "inherit" }}>You also agree to receive all communications from third parties regarding the service by email, postal mail or your telephone.
                    </font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>We may use your information to carry out TeeApp research activities to develop services to better serve you.</font></font></li>

                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 17. PRIVACY POLICY ON TEEAPP SOCIAL NETWORK</font></font></h3>
                <p><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>We always try to meet the requirements of Vietnamese law on the protection of personal information as specified in the Privacy Policy on personal information on social networks TeeApp within our ability. </font><font style={{ verticalAlign: "inherit" }}>In the event of force majeure and/or the impact of factors beyond our control, we will not be responsible for your personal information being disclosed.</font></font></p>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 18. INTELLECTUAL PROPERTY RIGHTS</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>We own intellectual property rights, including but not limited to copyright, related rights, trademarks, anti-unfair competition rights, trade secrets, and other intellectual property rights in all services of TeeApp. </font><font style={{ verticalAlign: "inherit" }}>Use of any object of TeeApp intellectual property rights requires our prior written permission.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>We do not grant any other license, express or implied, for you to exercise the above rights, other than expressly granted in writing. </font><font style={{ verticalAlign: "inherit" }}>And therefore, you do not have the right to use TeeApp's services for any purpose without our written permission.</font></font></li>
                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 19. RESERVATION OF INFORMATION PROCESSING RIGHT</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>In areas where Information is allowed to be shared, you may share the Information that is allowed in the formats we default to, and you are solely responsible for the information shared, communication regarding legality, as well as legal responsibilities for the Information you share with individual users or groups of users.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>We act as a passive guide for the online presentation and publicity of User Shared Information so in all cases we reserve the right to handle the Shared Information accordingly. accordance with this Agreement and the laws of Vietnam. </font><font style={{ verticalAlign: "inherit" }}>If the Information shared by the user is not in accordance with the terms and conditions of this Agreement, we may correct or immediately remove (delete) such Information and notify the relevant authority. function if necessary.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>The processing of our Shared Information complies with the procedures and policies based on the provisions of Vietnamese law to ensure the rights and interests of you as well as other individuals and organizations. </font><font style={{ verticalAlign: "inherit" }}>We are obliged and responsible for processing the Shared Information at the request of the competent state agency and/or in accordance with the laws of Vietnam.</font></font></li>
                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 20. AMENDMENTS AND SUPPLEMENTS</font></font></h3>
                <p><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>The terms of this Agreement may be amended or supplemented by us at any time without prior notice to you. </font><font style={{ verticalAlign: "inherit" }}>The revised and supplemented information will be published by us on the TeeApp Social Network.</font></font></p>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 21. EFFECTIVENESS</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>This Agreement is binding on you from the time of completing the registration for a TeeApp Social Network account.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>In the event that one or several provisions of this Agreement conflict with the provisions of law and are declared invalid by a competent court of Vietnam in accordance with the laws of Vietnam, the provision shall be declared invalid. such Agreement shall be amended to conform with the laws of Vietnam, and the remaining provisions of this Agreement shall remain in full force and effect.</font></font></li>
                </ol>
                <h3 class="teeapp-subtitle text-green-500"><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>ARTICLE 22. PAYMENT</font></font></h3>
                <ol>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Overview: TeeApp may offer products and services for purchase ("in-app purchases") through Apple Pay, Google Play, or other payment platforms authorized by TeeApp. </font><font style={{ verticalAlign: "inherit" }}>Claims for payments already made should be directed to Customer Support if you are being paid by TeeApp directly or through the relevant third-party account. </font><font style={{ verticalAlign: "inherit" }}>You may also make a complaint by contacting your payment service provider, who can provide more information about your rights and appropriate time limits.</font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>Virtual items: you can buy virtual items and use them in some functions on TeeApp. </font><font style={{ verticalAlign: "inherit" }}>The remaining amount of Virtual Items displayed in your account does not translate into a real-world balance or reflect any stored value, but instead constitutes a measure of the paper extent your permission. </font><font style={{ verticalAlign: "inherit" }}>Virtual Items incur no cost when not in use, however, the license granted to you in Virtual Items will terminate under the terms of this Agreement, when TeeApp ceases to provide the Services or the account. Your account is closed or terminated.
                    </font></font><br /><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>
                        TeeApp reserves the right to charge a fee for access or use of Virtual Items and/or may distribute Virtual Items with or without charge. </font><font style={{ verticalAlign: "inherit" }}>TeeApp may manage, regulate, control, modify or remove Virtual Items at any time. </font><font style={{ verticalAlign: "inherit" }}>TeeApp shall have no liability to you or any third party in the event TeeApp exercises the foregoing rights. </font><font style={{ verticalAlign: "inherit" }}>Virtual Items may only be redeemed through the Service. </font><font style={{ verticalAlign: "inherit" }}>ALL BUYING AND EXCHANGE OF VIRTUAL PRODUCTS PERFORMED THROUGH THE SERVICE IS FINAL AND NON-REFUNDABLE.
                            </font></font><br /><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>
                                The provision of Virtual Items for use in the Service is a service that commences upon acceptance of such Virtual Items. </font><font style={{ verticalAlign: "inherit" }}>YOU CONFIRM THAT TeeApp DOES NOT RECEIVE NO REFUND RELATED TO VIRTUAL ITEMS FOR ANY REASON AND YOU WILL NOT RECEIVE MONEY OR OTHER COMPENSATION FOR UNUSED VIRTUAL ITEM FOR ANY REASON IT IS VOLUNTARY OR NOT VOLUNTARY.
                            </font></font></li>
                    <li><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>
                        Refunds: generally, all purchases are non-refundable. Virtual Items purchases are FINAL AND NON-REFUNDABLE.
                    </font></font><br /><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>
                        However, you can contact a third party for refund advice. </font><font style={{ verticalAlign: "inherit" }}>If you signed up with your Apple ID, the refund will be handled by Apple, not TeeApp. </font><font style={{ verticalAlign: "inherit" }}>To request a refund, go to iTunes, tap your Apple ID, select Purchase History, find the transaction, and tap "Report a Problem." </font><font style={{ verticalAlign: "inherit" }}>You can also submit a request at https://getsupport.apple.com.
                            </font></font><br /><font style={{ verticalAlign: "inherit" }}><font style={{ verticalAlign: "inherit" }}>
                                If you signed up with a Google Play Store account: please contact customer support with your order number to Google Play Store (you can find the order number in your order confirmation email or log in Google Wallet) or TeeApp (this can be found in the confirmation email). </font><font style={{ verticalAlign: "inherit" }}>You can also mail or provide signed notice and provide information about purchase date, purchaser, order value. </font><font style={{ verticalAlign: "inherit" }}>Please specify the email address or phone number associated with your TeeApp account.
                            </font></font>
                    </li>
                </ol>
            </div>
        </main>
    )
}

export default Policy;